name: Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  change-detect:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: read
    outputs:
      duplicate_check: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          concurrent_skipping: 'always'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule", "merge_group"]'

  build:
    needs: change-detect
    if: needs.change-detect.outputs.duplicate_check != 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test
